# Generated by Django 3.1.4 on 2020-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('primarykey', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
