# Generated by Django 3.1.4 on 2020-12-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
    ]
