# Generated by Django 3.1.4 on 2020-12-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201217_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcPropertiesTable',
            fields=[
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
                ('properties', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calc_properties_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturesTable',
            fields=[
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
                ('features', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'features_table',
                'managed': False,
            },
        ),
    ]
